import type { FlowDocument } from '../types';

export const EXAMPLE_FLOWS: Record<string, any> = {
  customer_support: {
    flowId: 'customer-support-template',
    name: 'Customer Support Bot',
    version: 1,
    status: 'draft',
    trigger: { type: 'manual' },
    nodes: [
      {
        id: 'trigger_1',
        type: 'trigger',
        position: { x: 400, y: 50 },
        data: {
          label: 'User Starts Chat',
          nodeType: 'trigger',
          category: 'trigger',
          icon: '⚡',
          isConfigured: true,
          hasError: false,
          triggerType: 'manual',
          config: {},
        },
      },
      {
        id: 'welcome_text',
        type: 'text',
        position: { x: 400, y: 200 },
        data: {
          label: 'Welcome Message',
          nodeType: 'text',
          category: 'message',
          icon: '💬',
          isConfigured: true,
          hasError: false,
          message: 'Hello! Welcome to our support. How can we help you today?',
          variables: [],
        },
      },
      {
        id: 'choice_buttons',
        type: 'button',
        position: { x: 400, y: 350 },
        data: {
          label: 'Support vs Sales',
          nodeType: 'button',
          category: 'message',
          icon: '🔘',
          isConfigured: true,
          hasError: false,
          message: 'Please select a department:',
          buttons: [
            { id: 'btn_support', label: 'Support', value: 'support', type: 'reply' },
            { id: 'btn_sales', label: 'Sales', value: 'sales', type: 'reply' },
          ],
        },
      },
      {
        id: 'check_support',
        type: 'condition',
        position: { x: 400, y: 550 },
        data: {
          label: 'Is Support?',
          nodeType: 'condition',
          category: 'logic',
          icon: '🔀',
          isConfigured: true,
          hasError: false,
          combinator: 'and',
          rules: [
            { id: 'rule_1', field: 'last_button_click', operator: 'equals', value: 'support' },
          ],
        },
      },
      {
        id: 'ask_problem',
        type: 'inputRequest',
        position: { x: 200, y: 750 },
        data: {
          label: 'Ask for Problem',
          nodeType: 'inputRequest',
          category: 'message',
          icon: '📝',
          isConfigured: true,
          hasError: false,
          prompt: 'Please describe the issue you are facing:',
          variableName: 'user_problem',
          inputType: 'text',
          validation: { required: true },
        },
      },
      {
        id: 'sales_text',
        type: 'text',
        position: { x: 600, y: 750 },
        data: {
          label: 'Sales Redirect',
          nodeType: 'text',
          category: 'message',
          icon: '💬',
          isConfigured: true,
          hasError: false,
          message: 'Connecting you to our sales team...',
          variables: [],
        },
      },
      {
        id: 'ai_analysis',
        type: 'aiPrompt',
        position: { x: 200, y: 950 },
        data: {
          label: 'AI Problem Analysis',
          nodeType: 'aiPrompt',
          category: 'action',
          icon: '🤖',
          isConfigured: true,
          hasError: false,
          prompt: 'The user has the following problem: {{user_problem}}. Summarize this for a support agent and suggest 3 possible solutions.',
          model: 'gpt-4',
          responseVariable: 'ai_suggestion',
          temperature: 0.7,
        },
      },
      {
        id: 'notify_agent',
        type: 'notification',
        position: { x: 200, y: 1150 },
        data: {
          label: 'Notify Support Agent',
          nodeType: 'notification',
          category: 'action',
          icon: '🔔',
          isConfigured: true,
          hasError: false,
          channel: 'inApp',
          title: 'New Support Ticket',
          message: 'AI Summary: {{ai_suggestion}}',
          target: 'support_team',
        },
      },
      {
        id: 'end_flow',
        type: 'end',
        position: { x: 400, y: 1350 },
        data: {
          label: 'End Chat',
          nodeType: 'end',
          category: 'utility',
          icon: '🏁',
          isConfigured: true,
          hasError: false,
          endType: 'complete',
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'trigger_1', target: 'welcome_text', animated: true },
      { id: 'e2', source: 'welcome_text', target: 'choice_buttons', animated: true },
      { id: 'e3', source: 'choice_buttons', target: 'check_support', animated: true },
      { id: 'e4', source: 'check_support', target: 'ask_problem', sourceHandle: 'true', animated: true },
      { id: 'e5', source: 'check_support', target: 'sales_text', sourceHandle: 'false', animated: true },
      { id: 'e6', source: 'ask_problem', target: 'ai_analysis', animated: true },
      { id: 'e7', source: 'ai_analysis', target: 'notify_agent', animated: true },
      { id: 'e8', source: 'notify_agent', target: 'end_flow', animated: true },
      { id: 'e9', source: 'sales_text', target: 'end_flow', animated: true },
    ],
    variables: {
      user_problem: { name: 'user_problem', type: 'string', scope: 'flow' },
      ai_suggestion: { name: 'ai_suggestion', type: 'string', scope: 'flow' },
    },
    metadata: {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      description: 'A comprehensive support flow with AI analysis and agent notification.',
    },
  },
  lead_gen: {
    flowId: 'lead-gen-template',
    name: 'Lead Generation Funnel',
    version: 1,
    status: 'draft',
    trigger: { type: 'manual' },
    nodes: [
      {
        id: 'trigger_1',
        type: 'trigger',
        position: { x: 400, y: 50 },
        data: {
          label: 'Website Visit',
          nodeType: 'trigger',
          category: 'trigger',
          icon: '⚡',
          isConfigured: true,
          hasError: false,
          triggerType: 'manual',
          config: {},
        },
      },
      {
        id: 'lead_form',
        type: 'form',
        position: { x: 400, y: 200 },
        data: {
          label: 'Lead Capture Form',
          nodeType: 'form',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          title: 'Get Free Quote',
          description: 'Fill in your details to receive a personalized quote.',
          fields: [
            { id: 'f1', label: 'Name', name: 'name', type: 'text', required: true },
            { id: 'f2', label: 'Email', name: 'email', type: 'email', required: true },
            { id: 'f3', label: 'Budget', name: 'budget', type: 'number', required: true },
          ],
          submitLabel: 'Get Quote',
        },
      },
      {
        id: 'save_lead',
        type: 'databaseAction',
        position: { x: 400, y: 450 },
        data: {
          label: 'Save to CRM',
          nodeType: 'databaseAction',
          category: 'action',
          icon: '🗃️',
          isConfigured: true,
          hasError: false,
          action: 'insert',
          resource: 'leads',
          data: '{ "name": "{{name}}", "email": "{{email}}", "budget": {{budget}} }',
          resultVariable: 'db_result',
        },
      },
      {
        id: 'check_budget',
        type: 'condition',
        position: { x: 400, y: 650 },
        data: {
          label: 'High Budget?',
          nodeType: 'condition',
          category: 'logic',
          icon: '🔀',
          isConfigured: true,
          hasError: false,
          combinator: 'and',
          rules: [
            { id: 'r1', field: 'budget', operator: 'greaterThan', value: '1000' },
          ],
        },
      },
      {
        id: 'email_high',
        type: 'sendEmail',
        position: { x: 200, y: 850 },
        data: {
          label: 'VIP Welcome',
          nodeType: 'sendEmail',
          category: 'action',
          icon: '📧',
          isConfigured: true,
          hasError: false,
          to: '{{email}}',
          subject: 'Exclusive Offer for You!',
          body: 'Hi {{name}}, we noticed you have a significant budget. We would like to offer you a private consultation.',
          isHtml: true,
        },
      },
      {
        id: 'email_standard',
        type: 'sendEmail',
        position: { x: 600, y: 850 },
        data: {
          label: 'Standard Welcome',
          nodeType: 'sendEmail',
          category: 'action',
          icon: '📧',
          isConfigured: true,
          hasError: false,
          to: '{{email}}',
          subject: 'Welcome to our platform',
          body: 'Hi {{name}}, thanks for your interest. Here is your quote...',
          isHtml: true,
        },
      },
      {
        id: 'end_node',
        type: 'end',
        position: { x: 400, y: 1100 },
        data: {
          label: 'Finish',
          nodeType: 'end',
          category: 'utility',
          icon: '🏁',
          isConfigured: true,
          hasError: false,
          endType: 'complete',
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'trigger_1', target: 'lead_form', animated: true },
      { id: 'e2', source: 'lead_form', target: 'save_lead', animated: true },
      { id: 'e3', source: 'save_lead', target: 'check_budget', animated: true },
      { id: 'e4', source: 'check_budget', target: 'email_high', sourceHandle: 'true', animated: true },
      { id: 'e5', source: 'check_budget', target: 'email_standard', sourceHandle: 'false', animated: true },
      { id: 'e6', source: 'email_high', target: 'end_node', animated: true },
      { id: 'e7', source: 'email_standard', target: 'end_node', animated: true },
    ],
    variables: {
      name: { name: 'name', type: 'string', scope: 'flow' },
      email: { name: 'email', type: 'string', scope: 'flow' },
      budget: { name: 'budget', type: 'number', scope: 'flow' },
    },
    metadata: {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      description: 'Capture leads, save to DB, and send personalized emails based on budget.',
    },
  },
  auto_reply: {
    flowId: 'auto-reply-template',
    name: 'Auto-Reply Bot',
    version: 1,
    status: 'draft',
    trigger: { type: 'manual' },
    nodes: [
      {
        id: 'trigger_1',
        type: 'trigger',
        position: { x: 400, y: 50 },
        data: {
          label: 'Keyword: "Price"',
          nodeType: 'trigger',
          category: 'trigger',
          icon: '⚡',
          isConfigured: true,
          hasError: false,
          triggerType: 'keyword',
          config: { keyword: 'price' },
        },
      },
      {
        id: 'price_card',
        type: 'card',
        position: { x: 400, y: 200 },
        data: {
          label: 'Pricing Info',
          nodeType: 'card',
          category: 'message',
          icon: '🃏',
          isConfigured: true,
          hasError: false,
          title: 'Our Pricing Plans',
          subtitle: 'Choose the best plan for you',
          body: 'We offer Basic ($10/mo), Pro ($25/mo), and Enterprise (Custom) plans.',
          imageUrl: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=800&auto=format&fit=crop&q=60',
          layout: 'vertical',
          buttons: [
            { id: 'btn_basic', label: 'Basic Plan', value: 'basic', type: 'url' },
            { id: 'btn_pro', label: 'Pro Plan', value: 'pro', type: 'url' },
          ],
        },
      },
      {
        id: 'delay_node',
        type: 'delay',
        position: { x: 400, y: 450 },
        data: {
          label: 'Wait for User',
          nodeType: 'delay',
          category: 'logic',
          icon: '⏱️',
          isConfigured: true,
          hasError: false,
          duration: 10,
          unit: 'seconds',
        },
      },
      {
        id: 'followup_text',
        type: 'text',
        position: { x: 400, y: 600 },
        data: {
          label: 'Follow up',
          nodeType: 'text',
          category: 'message',
          icon: '💬',
          isConfigured: true,
          hasError: false,
          message: 'Did you find what you were looking for? Reply with "YES" or "NO".',
          variables: [],
        },
      },
      {
        id: 'end_node',
        type: 'end',
        position: { x: 400, y: 800 },
        data: {
          label: 'End',
          nodeType: 'end',
          category: 'utility',
          icon: '🏁',
          isConfigured: true,
          hasError: false,
          endType: 'complete',
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'trigger_1', target: 'price_card', animated: true },
      { id: 'e2', source: 'price_card', target: 'delay_node', animated: true },
      { id: 'e3', source: 'delay_node', target: 'followup_text', animated: true },
      { id: 'e4', source: 'followup_text', target: 'end_node', animated: true },
    ],
    variables: {},
    metadata: {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      description: 'Automatically replies to pricing inquiries with a rich card and follow-up.',
    },
  },
  survey_builder: {
    flowId: 'survey-builder-template',
    name: 'Survey Builder (Senior Eng)',
    version: 1,
    status: 'draft',
    trigger: { type: 'manual' },
    nodes: [
      {
        id: 'trigger_1',
        type: 'trigger',
        position: { x: 400, y: 50 },
        data: {
          label: 'Survey Starts',
          nodeType: 'trigger',
          category: 'trigger',
          icon: '⚡',
          isConfigured: true,
          hasError: false,
          triggerType: 'manual',
          config: {},
        },
      },
      {
        id: 'q_lang',
        type: 'questionnaire',
        position: { x: 400, y: 200 },
        data: {
          label: 'Select Language',
          nodeType: 'questionnaire',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          pIndex: 0,
          promptKey: 'select_language',
          language: 'ENGLISH',
          text: 'Please select your preferred language.',
          promptProps: ['SINGLE_CHOICE'],
          answers: [
            { id: 'ans_en', aIndex: 1, keyPattern: '1', keyPatternHuman: '1', text: 'ENGLISH', props: ['BUTTON'] },
            { id: 'ans_ta', aIndex: 2, keyPattern: '2', keyPatternHuman: '2', text: 'TAMIL', props: ['BUTTON'] },
          ],
        },
      },
      {
        id: 'q_age',
        type: 'questionnaire',
        position: { x: 400, y: 400 },
        data: {
          label: 'Age Range',
          nodeType: 'questionnaire',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          pIndex: 1,
          promptKey: 'age_range',
          language: 'ENGLISH',
          text: 'What is your age range?',
          promptProps: ['SINGLE_CHOICE'],
          answers: [
            { id: 'ans_under18', aIndex: 1, keyPattern: '1', keyPatternHuman: '1', text: '0 - 17', props: ['RADIO'] },
            { id: 'ans_over18', aIndex: 2, keyPattern: '2', keyPatternHuman: '2', text: '18 - 25', props: ['RADIO'] },
          ],
        },
      },
      {
        id: 'q_feedback',
        type: 'questionnaire',
        position: { x: 600, y: 600 },
        data: {
          label: 'User Feedback',
          nodeType: 'questionnaire',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          pIndex: 2,
          promptKey: 'user_feedback',
          language: 'ENGLISH',
          text: 'Since you are an adult, how would you rate our service?',
          promptProps: ['SINGLE_CHOICE'],
          answers: [
            { id: 'ans_good', aIndex: 1, keyPattern: '1', keyPatternHuman: '1', text: 'Good', props: ['BUTTON'] },
          ],
        },
      },
      {
        id: 'q_end',
        type: 'questionnaire',
        position: { x: 300, y: 800 },
        data: {
          label: 'End Thank You',
          nodeType: 'questionnaire',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          pIndex: 99,
          promptKey: 'end_thank_you',
          language: 'ENGLISH',
          text: 'Thank you for participating in this survey. Goodbye!',
          promptProps: ['ENDING'],
          answers: [],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'trigger_1', target: 'q_lang', animated: true },
      { id: 'e2', source: 'q_lang', sourceHandle: 'ans_en', target: 'q_age', animated: true },
      { id: 'e3', source: 'q_lang', sourceHandle: 'ans_ta', target: 'q_age', animated: true },
      { id: 'e4', source: 'q_age', sourceHandle: 'ans_under18', target: 'q_end', animated: true },
      { id: 'e5', source: 'q_age', sourceHandle: 'ans_over18', target: 'q_feedback', animated: true },
      { id: 'e6', source: 'q_feedback', sourceHandle: 'ans_good', target: 'q_end', animated: true },
    ],
    variables: {},
    metadata: {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      description: 'A pre-configured template replicating the exact JSON structure for the Questionnaire Builder.',
    },
  },
};
