import type { FlowDocument } from '../types';

// ─── Example Templates ───
// Templates use nodes/edges format (internal canvas format).
// Button/Card nodes have per-button output handles — no condition nodes needed.

export const EXAMPLE_FLOWS: Record<string, any> = {
  // ─── Customer Support: uses Button Choice for routing ───
  customer_support: {
    flowId: 'customer-support-template',
    name: 'Customer Support Bot',
    version: 1,
    status: 'draft',
    nodes: [
      {
        id: 'trigger_1',
        type: 'trigger',
        position: { x: 400, y: 50 },
        data: {
          label: 'Chat Starts',
          nodeType: 'trigger',
          category: 'trigger',
          icon: '⚡',
          isConfigured: true,
          hasError: false,
        },
      },
      {
        id: 'welcome_text',
        type: 'text',
        position: { x: 400, y: 180 },
        data: {
          label: 'Welcome Message',
          nodeType: 'text',
          category: 'message',
          icon: '💬',
          isConfigured: true,
          hasError: false,
          message: 'Hello! Welcome to our support. How can we help you today?',
          variables: [],
        },
      },
      {
        id: 'dept_buttons',
        type: 'button',
        position: { x: 400, y: 340 },
        data: {
          label: 'Choose Department',
          nodeType: 'button',
          category: 'message',
          icon: '🔘',
          isConfigured: true,
          hasError: false,
          message: 'Please select a department:',
          buttons: [
            { id: 'btn_support', label: 'Support', value: 'support', type: 'reply' },
            { id: 'btn_sales', label: 'Sales', value: 'sales', type: 'reply' },
            { id: 'btn_hr', label: 'HR', value: 'hr', type: 'reply' },
          ],
        },
      },
      {
        id: 'support_msg',
        type: 'text',
        position: { x: 150, y: 550 },
        data: {
          label: 'Support Reply',
          nodeType: 'text',
          category: 'message',
          icon: '💬',
          isConfigured: true,
          hasError: false,
          message: 'Our support team will assist you shortly. Please describe your issue.',
          variables: [],
        },
      },
      {
        id: 'sales_msg',
        type: 'text',
        position: { x: 400, y: 550 },
        data: {
          label: 'Sales Reply',
          nodeType: 'text',
          category: 'message',
          icon: '💬',
          isConfigured: true,
          hasError: false,
          message: 'Thanks for your interest! A sales representative will contact you.',
          variables: [],
        },
      },
      {
        id: 'hr_msg',
        type: 'text',
        position: { x: 650, y: 550 },
        data: {
          label: 'HR Reply',
          nodeType: 'text',
          category: 'message',
          icon: '💬',
          isConfigured: true,
          hasError: false,
          message: 'Please describe your HR inquiry and we will get back to you.',
          variables: [],
        },
      },
      {
        id: 'end_1',
        type: 'end',
        position: { x: 400, y: 720 },
        data: {
          label: 'End',
          nodeType: 'end',
          category: 'utility',
          icon: '🏁',
          isConfigured: true,
          hasError: false,
          endType: 'complete',
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'trigger_1', target: 'welcome_text', type: 'smoothstep', animated: true },
      { id: 'e2', source: 'welcome_text', target: 'dept_buttons', type: 'smoothstep', animated: true },
      // Each button connects to a different path — no condition needed!
      { id: 'e3', source: 'dept_buttons', sourceHandle: 'btn_support', target: 'support_msg', type: 'smoothstep', animated: true },
      { id: 'e4', source: 'dept_buttons', sourceHandle: 'btn_sales', target: 'sales_msg', type: 'smoothstep', animated: true },
      { id: 'e5', source: 'dept_buttons', sourceHandle: 'btn_hr', target: 'hr_msg', type: 'smoothstep', animated: true },
      { id: 'e6', source: 'support_msg', target: 'end_1', type: 'smoothstep', animated: true },
      { id: 'e7', source: 'sales_msg', target: 'end_1', type: 'smoothstep', animated: true },
      { id: 'e8', source: 'hr_msg', target: 'end_1', type: 'smoothstep', animated: true },
    ],
    variables: {},
    metadata: {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      description: 'Routes users via button choices — no conditions needed.',
    },
  },

  // ─── Language Survey: uses Survey Prompt for structured questionnaire ───
  survey_builder: {
    flowId: 'survey-builder-template',
    name: 'Language Survey',
    version: 1,
    status: 'draft',
    nodes: [
      {
        id: 'trigger_1',
        type: 'trigger',
        position: { x: 400, y: 50 },
        data: {
          label: 'Survey Starts',
          nodeType: 'trigger',
          category: 'trigger',
          icon: '⚡',
          isConfigured: true,
          hasError: false,
        },
      },
      {
        id: 'q_lang',
        type: 'questionnaire',
        position: { x: 400, y: 200 },
        data: {
          label: 'Select Language',
          nodeType: 'questionnaire',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          pIndex: 0,
          promptKey: 'select_language',
          language: 'ENGLISH',
          text: 'Please select your preferred language.',
          promptProps: ['SINGLE_CHOICE'],
          answers: [
            { id: 'ans_en', aIndex: 1, keyPattern: '1', keyPatternHuman: '1', text: 'ENGLISH', props: ['BUTTON'] },
            { id: 'ans_ta', aIndex: 2, keyPattern: '2', keyPatternHuman: '2', text: 'TAMIL', props: ['BUTTON'] },
          ],
        },
      },
      {
        id: 'q_age',
        type: 'questionnaire',
        position: { x: 400, y: 420 },
        data: {
          label: 'Age Range',
          nodeType: 'questionnaire',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          pIndex: 1,
          promptKey: 'age_range',
          language: 'ENGLISH',
          text: 'What is your age range?',
          promptProps: ['SINGLE_CHOICE'],
          answers: [
            { id: 'ans_u18', aIndex: 1, keyPattern: '1', keyPatternHuman: '1', text: '0 - 17', props: ['RADIO'] },
            { id: 'ans_1825', aIndex: 2, keyPattern: '2', keyPatternHuman: '2', text: '18 - 25', props: ['RADIO'] },
            { id: 'ans_2640', aIndex: 3, keyPattern: '3', keyPatternHuman: '3', text: '26 - 40', props: ['RADIO'] },
          ],
        },
      },
      {
        id: 'q_thanks',
        type: 'questionnaire',
        position: { x: 400, y: 640 },
        data: {
          label: 'Thank You',
          nodeType: 'questionnaire',
          category: 'message',
          icon: '📋',
          isConfigured: true,
          hasError: false,
          pIndex: 99,
          promptKey: 'end_thank_you',
          language: 'ENGLISH',
          text: 'Thank you for participating! Goodbye.',
          promptProps: ['ENDING'],
          answers: [],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'trigger_1', target: 'q_lang', type: 'smoothstep', animated: true },
      { id: 'e2', source: 'q_lang', sourceHandle: 'ans_en', target: 'q_age', type: 'smoothstep', animated: true },
      { id: 'e3', source: 'q_lang', sourceHandle: 'ans_ta', target: 'q_age', type: 'smoothstep', animated: true },
      { id: 'e4', source: 'q_age', sourceHandle: 'ans_u18', target: 'q_thanks', type: 'smoothstep', animated: true },
      { id: 'e5', source: 'q_age', sourceHandle: 'ans_1825', target: 'q_thanks', type: 'smoothstep', animated: true },
      { id: 'e6', source: 'q_age', sourceHandle: 'ans_2640', target: 'q_thanks', type: 'smoothstep', animated: true },
    ],
    variables: {},
    metadata: {
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      description: 'Structured survey with language selection and age routing.',
    },
  },
};
