import type { NodeLibraryItem, NodeCategory } from '../types';

export const NODE_CATEGORIES: { id: NodeCategory; label: string; icon: string }[] = [
  { id: 'trigger', label: 'Triggers', icon: '⚡' },
  { id: 'message', label: 'Messages', icon: '💬' },
  { id: 'logic', label: 'Logic', icon: '🔀' },
  { id: 'action', label: 'Actions', icon: '🚀' },
  { id: 'interaction', label: 'Human Interaction', icon: '👤' },
  { id: 'utility', label: 'Utility', icon: '🛠️' },
];

export const NODE_LIBRARY: NodeLibraryItem[] = [
  // ─── Trigger Nodes ───
  {
    type: 'trigger',
    label: 'Start Trigger',
    description: 'Entry point for your flow',
    category: 'trigger',
    icon: '⚡',
    color: '#10b981',
    defaultData: {
      label: 'Flow Start',
      nodeType: 'trigger',
      category: 'trigger',
      icon: '⚡',
      isConfigured: true,
      hasError: false,
    },
  },

  // ─── Message Nodes ───
  {
    type: 'text',
    label: 'Send Text',
    description: 'Send a text message',
    category: 'message',
    icon: '💬',
    color: '#3b82f6',
    defaultData: {
      label: 'Send Text',
      nodeType: 'text',
      category: 'message',
      icon: '💬',
      isConfigured: false,
      hasError: false,
      message: 'Hello! How can I help you?',
      variables: [],
    },
  },
  {
    type: 'button',
    label: 'Button Options',
    description: 'Show clickable buttons',
    category: 'message',
    icon: '🔘',
    color: '#8b5cf6',
    defaultData: {
      label: 'Button Options',
      nodeType: 'button',
      category: 'message',
      icon: '🔘',
      isConfigured: false,
      hasError: false,
      message: 'Please choose an option:',
      buttons: [
        { id: 'btn_1', label: 'Option 1', value: 'option_1', type: 'reply' },
        { id: 'btn_2', label: 'Option 2', value: 'option_2', type: 'reply' },
      ],
    },
  },
  {
    type: 'media',
    label: 'Send Media',
    description: 'Send image, video, or file',
    category: 'message',
    icon: '🖼️',
    color: '#06b6d4',
    defaultData: {
      label: 'Send Media',
      nodeType: 'media',
      category: 'message',
      icon: '🖼️',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'card',
    label: 'Card',
    description: 'Rich card with image & actions',
    category: 'message',
    icon: '🃏',
    color: '#f59e0b',
    defaultData: {
      label: 'Card',
      nodeType: 'card',
      category: 'message',
      icon: '🃏',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'carousel',
    label: 'Carousel',
    description: 'Swipeable card carousel',
    category: 'message',
    icon: '🎠',
    color: '#ec4899',
    defaultData: {
      label: 'Carousel',
      nodeType: 'carousel',
      category: 'message',
      icon: '🎠',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'form',
    label: 'Form',
    description: 'Collect structured data',
    category: 'message',
    icon: '📋',
    color: '#14b8a6',
    defaultData: {
      label: 'Form',
      nodeType: 'form',
      category: 'message',
      icon: '📋',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'inputRequest',
    label: 'Collect Input',
    description: 'Ask user for information',
    category: 'message',
    icon: '📝',
    color: '#6366f1',
    defaultData: {
      label: 'Collect Input',
      nodeType: 'inputRequest',
      category: 'message',
      icon: '📝',
      isConfigured: false,
      hasError: false,
      prompt: 'Please enter your information:',
      variableName: '',
      inputType: 'text',
      validation: { required: true },
    },
  },

  // ─── Logic Nodes ───
  {
    type: 'condition',
    label: 'Condition',
    description: 'If / Else branching',
    category: 'logic',
    icon: '🔀',
    color: '#f97316',
    defaultData: {
      label: 'Condition',
      nodeType: 'condition',
      category: 'logic',
      icon: '🔀',
      isConfigured: false,
      hasError: false,
      rules: [],
      combinator: 'and',
    },
  },
  {
    type: 'switch',
    label: 'Switch',
    description: 'Multiple path branching',
    category: 'logic',
    icon: '🔃',
    color: '#ea580c',
    defaultData: {
      label: 'Switch',
      nodeType: 'switch',
      category: 'logic',
      icon: '🔃',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'delay',
    label: 'Wait / Delay',
    description: 'Pause before next step',
    category: 'logic',
    icon: '⏱️',
    color: '#78716c',
    defaultData: {
      label: 'Wait',
      nodeType: 'delay',
      category: 'logic',
      icon: '⏱️',
      isConfigured: false,
      hasError: false,
      duration: 5,
      unit: 'seconds',
    },
  },
  {
    type: 'randomSplit',
    label: 'A/B Split',
    description: 'Randomly split flow',
    category: 'logic',
    icon: '🎲',
    color: '#d946ef',
    defaultData: {
      label: 'A/B Split',
      nodeType: 'randomSplit',
      category: 'logic',
      icon: '🎲',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'loop',
    label: 'Loop',
    description: 'Repeat steps',
    category: 'logic',
    icon: '🔁',
    color: '#0891b2',
    defaultData: {
      label: 'Loop',
      nodeType: 'loop',
      category: 'logic',
      icon: '🔁',
      isConfigured: false,
      hasError: false,
    },
  },

  // ─── Action Nodes ───
  {
    type: 'httpRequest',
    label: 'Send Request',
    description: 'Make an HTTP/API call',
    category: 'action',
    icon: '🌐',
    color: '#2563eb',
    defaultData: {
      label: 'Send Request',
      nodeType: 'httpRequest',
      category: 'action',
      icon: '🌐',
      isConfigured: false,
      hasError: false,
      url: '',
      method: 'GET',
      headers: {},
      body: '',
      responseVariable: 'response',
    },
  },
  {
    type: 'saveVariable',
    label: 'Save Variable',
    description: 'Store a value for later use',
    category: 'action',
    icon: '💾',
    color: '#059669',
    defaultData: {
      label: 'Save Variable',
      nodeType: 'saveVariable',
      category: 'action',
      icon: '💾',
      isConfigured: false,
      hasError: false,
      variableName: '',
      value: '',
      valueType: 'static',
    },
  },
  {
    type: 'sendEmail',
    label: 'Send Email',
    description: 'Send an email message',
    category: 'action',
    icon: '📧',
    color: '#dc2626',
    defaultData: {
      label: 'Send Email',
      nodeType: 'sendEmail',
      category: 'action',
      icon: '📧',
      isConfigured: false,
      hasError: false,
      to: '',
      subject: '',
      body: '',
      isHtml: false,
    },
  },
  {
    type: 'aiPrompt',
    label: 'AI Prompt',
    description: 'Generate AI response',
    category: 'action',
    icon: '🤖',
    color: '#7c3aed',
    defaultData: {
      label: 'AI Prompt',
      nodeType: 'aiPrompt',
      category: 'action',
      icon: '🤖',
      isConfigured: false,
      hasError: false,
      prompt: '',
      model: 'gpt-4',
      responseVariable: 'ai_response',
      temperature: 0.7,
    },
  },
  {
    type: 'databaseAction',
    label: 'Database Action',
    description: 'Read or write database',
    category: 'action',
    icon: '🗃️',
    color: '#0d9488',
    defaultData: {
      label: 'Database Action',
      nodeType: 'databaseAction',
      category: 'action',
      icon: '🗃️',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'notification',
    label: 'Send Notification',
    description: 'Push notification or alert',
    category: 'action',
    icon: '🔔',
    color: '#eab308',
    defaultData: {
      label: 'Send Notification',
      nodeType: 'notification',
      category: 'action',
      icon: '🔔',
      isConfigured: false,
      hasError: false,
      channel: 'inApp',
      title: '',
      message: '',
      target: '',
    },
  },

  // ─── Human Interaction ───
  {
    type: 'assignAgent',
    label: 'Assign Agent',
    description: 'Route to human agent',
    category: 'interaction',
    icon: '👤',
    color: '#7c3aed',
    defaultData: {
      label: 'Assign Agent',
      nodeType: 'assignAgent',
      category: 'interaction',
      icon: '👤',
      isConfigured: false,
      hasError: false,
      assignmentType: 'roundRobin',
    },
  },
  {
    type: 'approvalRequest',
    label: 'Request Approval',
    description: 'Wait for human approval',
    category: 'interaction',
    icon: '✅',
    color: '#16a34a',
    defaultData: {
      label: 'Request Approval',
      nodeType: 'approvalRequest',
      category: 'interaction',
      icon: '✅',
      isConfigured: false,
      hasError: false,
    },
  },
  {
    type: 'humanTakeover',
    label: 'Human Takeover',
    description: 'Transfer to live agent',
    category: 'interaction',
    icon: '🤝',
    color: '#e11d48',
    defaultData: {
      label: 'Human Takeover',
      nodeType: 'humanTakeover',
      category: 'interaction',
      icon: '🤝',
      isConfigured: false,
      hasError: false,
    },
  },

  // ─── Utility ───
  {
    type: 'notes',
    label: 'Note',
    description: 'Add a note to the canvas',
    category: 'utility',
    icon: '📌',
    color: '#fbbf24',
    defaultData: {
      label: 'Note',
      nodeType: 'notes',
      category: 'utility',
      icon: '📌',
      isConfigured: true,
      hasError: false,
      content: '',
      color: '#fef3c7',
    },
  },
  {
    type: 'end',
    label: 'End Flow',
    description: 'Terminate the flow',
    category: 'utility',
    icon: '🏁',
    color: '#ef4444',
    defaultData: {
      label: 'End',
      nodeType: 'end',
      category: 'utility',
      icon: '🏁',
      isConfigured: true,
      hasError: false,
      endType: 'complete',
    },
  },
];

export const getCategoryNodes = (category: NodeCategory): NodeLibraryItem[] =>
  NODE_LIBRARY.filter((n) => n.category === category);

export const getNodeColor = (type: string): string => {
  const item = NODE_LIBRARY.find((n) => n.type === type);
  return item?.color ?? '#6b7280';
};

export const getNodeIcon = (type: string): string => {
  const item = NODE_LIBRARY.find((n) => n.type === type);
  return item?.icon ?? '📦';
};
