import type { NodeCategory, NodeLibraryItem } from '../types';

export const NODE_CATEGORIES: { id: NodeCategory; label: string; icon: string }[] = [
  { id: 'trigger', label: 'Triggers', icon: '⚡' },
  { id: 'message', label: 'Messages', icon: '💬' },
  { id: 'logic', label: 'Logic', icon: '🔀' },
  { id: 'action', label: 'Actions', icon: '🚀' },
  { id: 'utility', label: 'Utility', icon: '🛠️' },
];

export const NODE_LIBRARY: NodeLibraryItem[] = [
  // ─── Trigger ───
  {
    type: 'trigger',
    label: 'Start Trigger',
    description: 'Entry point for your flow',
    category: 'trigger',
    icon: '⚡',
    color: '#10b981',
    defaultData: {
      label: 'Flow Start',
      nodeType: 'trigger',
      category: 'trigger',
      icon: '⚡',
      isConfigured: true,
      hasError: false,
    },
  },

  // ─── Message Nodes ───
  {
    type: 'text',
    label: 'Text Message',
    description: 'Send a simple text message',
    category: 'message',
    icon: '💬',
    color: '#3b82f6',
    defaultData: {
      label: 'Text Message',
      nodeType: 'text',
      category: 'message',
      icon: '💬',
      isConfigured: false,
      hasError: false,
      message: '',
      variables: [],
    } as any,
  },
  {
    type: 'button',
    label: 'Button Choice',
    description: 'Show buttons — each connects to a different path',
    category: 'message',
    icon: '🔘',
    color: '#8b5cf6',
    defaultData: {
      label: 'Button Choice',
      nodeType: 'button',
      category: 'message',
      icon: '🔘',
      isConfigured: false,
      hasError: false,
      message: 'Please choose:',
      buttons: [
        { id: 'btn_1', label: 'Option 1' },
        { id: 'btn_2', label: 'Option 2' },
      ],
    } as any,
  },
  {
    type: 'card',
    label: 'Card',
    description: 'Rich card with buttons that route to paths',
    category: 'message',
    icon: '🃏',
    color: '#f59e0b',
    defaultData: {
      label: 'Card',
      nodeType: 'card',
      category: 'message',
      icon: '🃏',
      isConfigured: false,
      hasError: false,
      title: 'Card Title',
      subtitle: '',
      body: '',
      imageUrl: '',
      layout: 'vertical',
      buttons: [],
    } as any,
  },
  {
    type: 'inputRequest',
    label: 'Collect Input',
    description: 'Ask user for text, email, number, etc.',
    category: 'message',
    icon: '📝',
    color: '#6366f1',
    defaultData: {
      label: 'Collect Input',
      nodeType: 'inputRequest',
      category: 'message',
      icon: '📝',
      isConfigured: false,
      hasError: false,
      prompt: 'Please enter your information:',
      variableName: '',
      inputType: 'text',
      validation: { required: true },
    } as any,
  },
  {
    type: 'questionnaire',
    label: 'Survey Prompt',
    description: 'Structured prompt for questionnaire flows',
    category: 'message',
    icon: '📋',
    color: '#8b5cf6',
    defaultData: {
      label: 'Survey Prompt',
      nodeType: 'questionnaire',
      category: 'message',
      icon: '📋',
      isConfigured: false,
      hasError: false,
      promptKey: '',
      language: 'ENGLISH',
      text: '',
      promptProps: ['SINGLE_CHOICE'],
      answers: [
        { id: 'ans_1', aIndex: 1, text: 'Option 1' },
      ],
    } as any,
  },

  // ─── Logic Nodes (kept for advanced users) ───
  {
    type: 'condition',
    label: 'Condition',
    description: 'Branch based on rules (Yes/No)',
    category: 'logic',
    icon: '🔀',
    color: '#f59e0b',
    defaultData: {
      label: 'Condition',
      nodeType: 'condition',
      category: 'logic',
      icon: '🔀',
      isConfigured: false,
      hasError: false,
      combinator: 'and',
      rules: [],
    } as any,
  },
  {
    type: 'delay',
    label: 'Delay',
    description: 'Wait before next step',
    category: 'logic',
    icon: '⏱️',
    color: '#f59e0b',
    defaultData: {
      label: 'Delay',
      nodeType: 'delay',
      category: 'logic',
      icon: '⏱️',
      isConfigured: true,
      hasError: false,
      duration: 5,
      unit: 'seconds',
    } as any,
  },

  // ─── Action Nodes ───
  {
    type: 'httpRequest',
    label: 'API Call',
    description: 'Make HTTP request to external API',
    category: 'action',
    icon: '🌐',
    color: '#8b5cf6',
    defaultData: {
      label: 'API Call',
      nodeType: 'httpRequest',
      category: 'action',
      icon: '🌐',
      isConfigured: false,
      hasError: false,
      method: 'GET',
      url: '',
      headers: {},
      body: '',
      responseVariable: 'api_response',
    } as any,
  },
  {
    type: 'sendEmail',
    label: 'Send Email',
    description: 'Send an email notification',
    category: 'action',
    icon: '📧',
    color: '#8b5cf6',
    defaultData: {
      label: 'Send Email',
      nodeType: 'sendEmail',
      category: 'action',
      icon: '📧',
      isConfigured: false,
      hasError: false,
      to: '',
      subject: '',
      body: '',
      isHtml: false,
    } as any,
  },
  {
    type: 'notification',
    label: 'Notification',
    description: 'Send push / SMS / in-app notification',
    category: 'action',
    icon: '🔔',
    color: '#8b5cf6',
    defaultData: {
      label: 'Notify',
      nodeType: 'notification',
      category: 'action',
      icon: '🔔',
      isConfigured: false,
      hasError: false,
      channel: 'push',
      title: '',
      message: '',
      target: '',
    } as any,
  },

  // ─── Utility Nodes ───
  {
    type: 'end',
    label: 'End Flow',
    description: 'Terminate the flow',
    category: 'utility',
    icon: '🏁',
    color: '#ef4444',
    defaultData: {
      label: 'End',
      nodeType: 'end',
      category: 'utility',
      icon: '🏁',
      isConfigured: true,
      hasError: false,
      endType: 'complete',
    } as any,
  },
  {
    type: 'notes',
    label: 'Sticky Note',
    description: 'Add a comment to the canvas',
    category: 'utility',
    icon: '📝',
    color: '#fef08a',
    defaultData: {
      label: 'Note',
      nodeType: 'notes',
      category: 'utility',
      icon: '📝',
      isConfigured: true,
      hasError: false,
      content: 'Write your notes here...',
      color: '#fef08a',
    } as any,
  },
];

// ─── Utility functions ───
export function getNodeColor(type: string): string {
  const node = NODE_LIBRARY.find((n) => n.type === type);
  return node ? node.color : '#94a3b8';
}

export function getCategoryNodes(category: NodeCategory): NodeLibraryItem[] {
  return NODE_LIBRARY.filter((n) => n.category === category);
}
